# Generated by Django 2.2 on 2019-06-12 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Security Need',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=100)),
                ('color', models.CharField(choices=[('R', 'Red'), ('O', 'Orange'), ('G', 'Green')], default='Green', max_length=100)),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='SecurityNeedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('type', models.CharField(default='None', max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.SecurityNeed', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Security Need Value',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='code')),
                ('description', models.TextField(default='')),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('contributors', models.ManyToManyField(related_name='contributors', to=settings.AUTH_USER_MODEL)),
                ('security_needs', models.ManyToManyField(related_name='project_item', to='basic.SecurityNeedValue')),
                ('tags', models.ManyToManyField(related_name='tags', to='basic.Tag')),
            ],
            options={
                'verbose_name': 'Projet',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('control_description', models.TextField()),
                ('applicable_securityneedvalue', models.ManyToManyField(to='basic.SecurityNeedValue')),
                ('applicable_tags', models.ManyToManyField(to='basic.Tag')),
            ],
            options={
                'verbose_name': 'Security Control',
                'verbose_name_plural': 'Security Controls',
            },
        ),
        migrations.CreateModel(
            name='ProjectControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.CharField(choices=[('A', 'Applicable'), ('NA', 'Not Applicable')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('D', 'Done'), ('NP', 'Not Planned'), ('P', 'Planned')], max_length=100)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Control', verbose_name='Controle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Control',
                'unique_together': {('project', 'control')},
            },
        ),
    ]
