# Generated by Django 2.1.3 on 2020-04-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20191127_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityneedvalue',
            name='type',
        ),
    ]
