# Generated by Django 2.2.12 on 2020-08-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_remove_securityneedvalue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='controls',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='controls', to='basic.Control'),
        ),
    ]
