# Generated by Django 2.2.12 on 2020-08-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20200830_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='controls',
        ),
        migrations.AddField(
            model_name='project',
            name='controls',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='controls', to='basic.ProjectControl'),
        ),
    ]
