# Generated by Django 2.2.13 on 2020-08-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20200830_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='controls',
        ),
    ]
